plugins {
  id 'scala'
  id 'application'
  id 'org.podval.conventions'
  id 'org.podval.tools.scalajs' version '2.3.0'
}

// Gradle 9.8.1 still defaults Zinc to 1.12.0.
scala.zincVersion = '1.12.1'

description = 'Process Photographs'
group = 'org.podval.tools'
version = '0.0.1'

project.gradle.startParameter.excludedTaskNames.add('compileJava')

dependencies {
//  implementation 'org.slf4j:slf4j-api:2.0.17'
  implementation 'com.drewnoakes:metadata-extractor:2.21.0'
  implementation 'dev.zio:zio-cli_3:0.8.2'
  implementation 'dev.zio:zio-schema_3:1.9.0'
  implementation 'dev.zio:zio-schema-derivation_3:1.9.0'
  //libraryDependencies += "org.scala-lang" % "scala-reflect"  % scalaVersion.value % "provided"
  implementation 'io.github.wasabithumb:jtoml:1.8.2'
  implementation 'com.google.photos.library:google-photos-library-client:1.7.3'
  testImplementation 'org.scalatest:scalatest_3:3.2.20'
}

application {
  mainClass = 'org.podval.tools.photo.Cli'
}

jar {
  manifest {
    attributes(
      'Implementation-Title'  : project.description,
      'Implementation-Version': project.version
    )
  }
}

tasks.register('sourcesJar', Jar) {
  from sourceSets.main.allSource
  archiveClassifier.set('sources')
}

tasks.register('scaladocJar', Jar) {
  from scaladoc.destinationDir
  archiveClassifier.set('scaladoc')
}
scaladocJar.dependsOn scaladoc
