= Google Photo Synchronization

Manage local photo collection and synchronize it with Google Photos.

I started dabbling in this area around year 2000,
when our daughter was born and I got my first digital camera :)

== TODO

- event management

== Metadata Extraction

My take on extracting metadata from image files is in the (now archived)
https://github.com/dubinsky/podval-imageio[podval-imageio] repository.

There, between 2003 and 2009, I worked on:

- extracting image metadata from the image file
- extracting thumbnails from the raw image file
- demosaicing raw images

There were some good ideas there:

- describing metadata structure in XML
- push and pull parsing of the metadata

I contributed small discoveries I made in 2002 about Canon RAW format (crw)
to David Burren.

In the end I realized: it does not make sense to do this myself
when there are groups of people who dedicate significant time
to developing and maintaining dedicated tools like
`dcraw`, `metadata-extractor` and `ffmpeg` :)

== Metadata Extraction Tools

- https://github.com/drewnoakes/metadata-extractor[metadata-extractor]
(originally, https://drewnoakes.com/code/exif/) by https://github.com/drewnoakes[Drew Noakes]
- http://www.burren.cx/david/canon.html[Canon EXIF Maker Note] by David Burren
- http://www.cybercom.net/~dcoffin/dcraw/[dcraw] by Dave Coffin
- libraw
- http://www.sno.phy.queensu.ca/~phil/exiftool/exiftool[ExifTool]
- ffprobe
- http://www.sentex.net/~mwandel/jhead/[jhead]
- http://jphoto.sourceforge.net/[Java USB Camera Tools]

== Synchronization with the Cloud

My previous attempt at code
to synchronize local photo archive with the cloud photo services
is in the (now archived)
https://github.com/dubinsky/podval-photo-sync[podval-photo-sync] repository.

There, between 2009 and 2011, I worked on:

- synchronizing with Zenfolio (which I no longer use)
- synchronizing with Picasa and Google+ (which no longer exist)
- expose locally recorded timestamp and image orientation to the cloud service

There were some good ideas there:

- group files belonging to the same picture (raw, jpg, metadata)
- use family polymorphism to abstract over cloud photo services

In the end, while chasing ever-changing cloud,
I neglected the management of the local photo archive -
something that this repository finally delivers.

Unfortunately, by now it is impossible to synchronize the local archive
with Google photos: in 2024, Google removed the necessary APIs :(

== Google Photos API

Too late!
- https://issuetracker.google.com/issues/368779600?pli=1


- https://rclone.org/googlephotos/[RClone Google Photo documentation]
- https://rclone.org/drive/#making-your-own-client-id[RClone Google Photo OAuth documentation]
- https://github.com/rclone/gphotosdl[RClone Download Proxy]
- https://developers.google.com/photos/library/guides/get-started-library[Google Photos API]
- https://developers.google.com/photos/overview/get-started-java[Google Photo Client Library]
- https://developers.google.com/photos/picker/guides/get-started-picker[NEW Picker API]

- list GPhotos pictures and albums
- record skipped pictures in the local metadata
- upload pictures
- create event albums and add pictures to them
