= TOML Codec

My attempt to implement a subset of the TOML
specification https://toml.io/en/v1.0.0 using ZIO Schema.

It does what I need; potential enhancements are:

- handle Toml encoding/decoding configuration
- implement streaming encoding/decoding
- encode and decode tuples to and from Toml tables
- decode Toml arrays to records
- look into some miraculous way to preserve comments
for the round trip (annotations?)
- productize the codec (rewrite in Scala 2 etc.)
and submit a pull request to ZIO Schema

== History

I started off with the https://github.com/indoorvivants/toml-scala library;
turns out, it can *parse* a string into a case class
but is not able to *write* a case class to string
(see https://github.com/indoorvivants/toml-scala/issues/10):
to write TOML using it, one has to hand-convert it to the `toml-scala` AST;
I do not want to do that ;)

There is no official TOML codec for ZIO Schema, so I had to make my own.

I *really* do not want to deal directly with the TOML syntax;
like ZIO Schema codecs for other formats do,
I want to delegate reading and writing
to a well-maintained library that supports current version of TOML;
Google searches and official list of
https://github.com/toml-lang/toml/wiki#implementations[TOML implementations]
netted the following choices:

- https://github.com/indoorvivants/toml-scala
- https://github.com/FasterXML/jackson-dataformats-text
- https://github.com/TheElectronWill/Night-Config
- https://github.com/tomlj/tomlj
- https://github.com/WasabiThumb/jtoml

I decided to go with `WasabiThumb/jtoml`, since it:
- claims latest TOML compatibility
- compares itself favorably to a number of other TOML implementations
- exposes a document model which can be parsed into and written from


